version: '3.9'

services:
  dev-db:
    image: postgres:13
    container_name: ${POSTGRES_DB}
    restart: always
    ports:
      - ${POSTGRES_DB_PORT}:5432
    env_file:
      - .env

  test-db:
    image: postgres:13
    container_name: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_DB_PORT}:5432
    env_file:
      - .env.test
